DROP TABLE IF EXISTS customer;
CREATE TABLE customer (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  age INT,
  course VARCHAR(100),
  password VARCHAR(100),
  data_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  data_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
