CREATE TABLE IF NOT EXISTS customer (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT,
  age INT,
  course VARCHAR(100),
  email VARCHAR(150),
  password VARCHAR(150),
  image_path VARCHAR(500) NULL,
  data_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  data_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
